<?php
return [
    'LIMIT_STRING_PRODUCT_DESCRIPTION' => 30,
    'LIMIT_STRING_DESCRIPTION' => 50,
    'SUPERADMIN_ROLE_ID' => 1,
    'MANAGER_ROLE_ID' => 2,
    'STAFF_ROLE_ID' => 3,
    'SUCCESSFUL_FLAG' => true,
    'UNSUCCESSFUL_FLAG' => false,
    'ACCOUNTS_PER_PAGES' => 21,
    'MALE_GENDER' => 1,
    'FEMALE_GENDER' => 0,
    'LIMIT_STRING_DESCRIPTION_75' => 75,
    'TEN_RECORDS' => 10,
    'FEMALE_GENDER' => 0,
    'MALE_GENDER' => 1,
    'IMAGE_WIDTH' => 200,
    'IMAGE_HEIGHT' => 200,
    'DATE_DMY_FORMAT' => 'd/m/Y',
    'DATE_DMY_FORMAT_DATE_PICKER' => 'DD/MM/YYYY',
    'DATE_YMD_FORMAT' => 'Y-m-d',
    'IS_ON_SALE_YES'=> 'Yes',
    'IS_ON_SALE_NO'=> 'No',
    'ON_SALE' => 1,
    'OFF_SALE' => 0,
    'AVATAR_PATH' => '/file/avatar',
    'INITAL_TIME' => ' 00:00:00',
    'TOP_4' => 4,
    'TOP_5' => 5,
    'ONE_HUNDRED' => 100,
    'SELECT_FIVE' => 5,
    'SELECT_TEN' => 10,
    'FOUR_NEWEST_QUARTER' => 4,
];
