<?php
return [
    'LIMIT_STRING_PRODUCT_DESCRIPTION' => 30,
    'LIMIT_STRING_DESCRIPTION' => 50,
    'SUPERADMIN_ROLE_ID' => 1,
    'MANAGER_ROLE_ID' => 2,
    'STAFF_ROLE_ID' => 3,
    'SUCCESSFUL_FLAG' => true,
    'UNSUCCESSFUL_FLAG' => false,
    'ACCOUNTS_PER_PAGES' => 21,
];
